language: android

jdk: oraclejdk8

sudo: false

env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

sdk_components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - build-tools-25.0.3
  - android-$EMULATOR_API_LEVEL
  - extra-android-m2repository
  - extra-android-support
  - sys-img-$ANDROID_ABI-android-23
  - extra-google-google_play_services

# I need to install the license for android-25 so I can use it
# in the project building phase; as seen in here:
# https://gist.github.com/harmittaa/7d3c51041ffd0e54cda9807e95593309
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license" # This license code was in my local license folder

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a --
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

before_cache: 
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"

before_install: 
  - "chmod +x gradlew"

cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew build connectedAndroidTest -S