language: android
jdk: oraclejdk8
env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

sdk_components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository


before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &


script: ./gradlew build connectedAndroidTest